### ISSUE TITLE
Property "progressColor" makes BufferSlider wrong completely.

### ISSUE THREAD

**Issue by raxcat** [raxcat/BufferSlider#3]
Commit 9f64f00 is making BufferSlider working wrong completely.

It comes to  
<img width="404" alt="2016-10-10 12 46 28" src="https://cloud.githubusercontent.com/assets/1287879/19222123/cad9ea80-8e83-11e6-9c5a-a05be7ce89fc.png">

This is not the correct. I will discard this commit and need times to add "progressColor" back.

**Comment by raxcat** [comment]
fixed in 13ad8f036619d0027e5062e3402c7e0cdfe0782d

**Comment by jamchen** [comment]
awesome
